name: "CI workflow"
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: "read"
jobs:
  # Composer config validation
  composer:
    name: Composer config validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate --strict
  # PHP syntax validation
  php:
    name: PHP syntax validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PHP syntax
        run: php -l src/ tests/
  # run PHP unit tests
  phpunit:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1, 8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
      - run: vendor/bin/phpunit